version: '3.7'

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=rentx_password
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      my_aplication:
        ipv4_address: 172.16.238.10
    #networks:
    #  - new
    #network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    depends_on:
      - database_rentx
    volumes:
      - .:/usr/app
    networks:
      my_aplication:
        ipv4_address: 172.16.238.11
    #networks:
    #  - new
    #network_mode: host

volumes:
  pgdata:

networks:
  my_aplication:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
